default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: chris
  password: 1234

development:
  <<: *default
  database: rent_master_chat_development

test:
  <<: *default
  database: rent_master_chat_test

production:
  <<: *default
  database: rent_master_chat_production
